sculpin_content_types:
    posts:
      enabled: true
      permalink: blog/:year/:month/:day/:slug_title
services:
  twig.extension.intl:
    class: Twig\Extra\Intl\IntlExtension
    tags:
      - { name: twig.extension }