title: "Moisés Fausto | Full Stack Developer | PHP | Laravel | Vue Js"
subtitle: "Sou desenvolvedor full stack, onde desenvolvo no Brasil a mais de 5 anos em grande empresas e projetos emergentes."
author: 'Moisés Fausto'
url: /portifolio
google_analytics_tracking_id: 'G-XWECERXMS6'

# Social info
social:
  email: moisesfausto@gmail.com
  linkedin: https://www.linkedin.com/in/moisesfausto/
  git: https://gitlab.com/moisesfausto
  link: https://beacons.ai/moisesfausto
